// Database types for Supabase
// This file is auto-generated by @nuxtjs/supabase
// If you need to generate types, run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
